drop table if exists review_reaction;
drop table if exists film_review;

drop table if exists friends;
drop table if exists likes;
drop table if exists users;
drop table if exists genre;
drop table if exists director_film;
drop table if exists films;
drop table if exists directors;


create table if not exists users
(
    user_id  integer generated by default as identity primary key,
    email    varchar not null unique,
    login    varchar not null unique,
    name     varchar not null,
    birthday date
);
create table if not exists friends
(
    user_id   integer not null,
    friend_id integer not null,
    primary key (user_id, friend_id),
    foreign key (user_id) references users (user_id) on delete cascade,
    foreign key (friend_id) references users (user_id) on delete cascade
);
create table if not exists genre_type
(
    genre_id integer generated by default as identity primary key,
    name     varchar not null unique
);
create table if not exists mpa
(
    mpa_rating_id integer generated by default as identity primary key,
    name          varchar not null unique
);
create table if not exists films
(
    film_id       integer generated by default as identity primary key,
    name          varchar not null,
    description   varchar,
    release_date  date,
    duration      integer not null,
    mpa_rating_id integer not null,
    rate          bigint,
    foreign key (mpa_rating_id) references mpa (mpa_rating_id)
);
create table if not exists directors
(
    director_id integer generated by default as identity primary key,
    name        varchar(64) not null
);
create table if not exists director_film
(
    film_id     integer not null,
    director_id integer not null,
    foreign key (film_id) references films (film_id) on delete cascade,
    foreign key (director_id) references directors (director_id) on delete cascade,
    primary key (film_id, director_id)
);
create table if not exists genre
(
    film_id  integer not null,
    genre_id integer not null,
    foreign key (film_id) references films (film_id) on delete cascade,
    foreign key (genre_id) references genre_type (genre_id) on delete cascade,
    primary key (film_id, genre_id)
);
create table if not exists likes
(
    film_id integer not null,
    user_id integer not null,
    primary key (film_id, user_id),
    foreign key (film_id) references films (film_id) on delete cascade,
    foreign key (user_id) references users (user_id) on delete cascade
);


CREATE TABLE IF NOT EXISTS film_review
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     varchar(4000),
    is_positive BOOLEAN,
    user_id     INTEGER references users (user_id) ON DELETE CASCADE,
    film_id     INTEGER references films (film_id) ON DELETE CASCADE,
    constraint unique_review unique (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS review_reaction
(
    review_id      INTEGER references film_review (id) ON DELETE CASCADE,
    user_id        INTEGER references users (user_id) ON DELETE CASCADE,
    reaction_value integer,
    primary key (review_id, user_id)
);
